DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Likes;
DROP TABLE IF EXISTS Song;
DROP TABLE IF EXISTS Created;
DROP TABLE IF EXISTS Follows;
DROP TABLE IF EXISTS Remix;
DROP TABLE IF EXISTS Artist;
DROP TABLE IF EXISTS Remixed;

CREATE TABLE User (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  FirstName TEXT NOT NULL,
  LastName TEXT NOT NULL,
  User_Email TEXT UNIQUE NOT NULL,
  Password TEXT NOT NULL
);

CREATE TABLE Song (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  SongName TEXT NOT NULL,
  Genre TEXT NOT NULL,
  Tempo TEXT NOT NULL
);

CREATE TABLE Remix (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Remix_Name TEXT NOT NULL,
  Link_Name TEXT NOT NULL
);

CREATE TABLE Artist (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Artist_Name TEXT NOT NULL
);

CREATE TABLE Created (
  User_Id INTEGER NOT NULL,
  Song_Id INTEGER NOT NULL,
  PRIMARY KEY(User_Id, Song_Id),
  FOREIGN KEY (User_Id) REFERENCES User(Id),
  FOREIGN KEY (Song_Id) REFERENCES Song(Id)
);

CREATE TABLE Follows (
  User_Id_1 INTEGER NOT NULL,
  User_Id_2 INTEGER NOT NULL,
  PRIMARY KEY(User_Id_1, User_Id_2),
  FOREIGN KEY (User_Id_1) REFERENCES User(Id),
  FOREIGN KEY (User_Id_2) REFERENCES Song(Id)
);

CREATE TABLE Likes (
  User_Id INTEGER NOT NULL,
  Song_Id INTEGER NOT NULL,
  PRIMARY KEY(User_Id, Song_Id),
  FOREIGN KEY (User_Id) REFERENCES User(Id),
  FOREIGN KEY (Song_Id) REFERENCES Song(Id)
);

CREATE TABLE Remixed (
  Remix_Id INTEGER NOT NULL,
  Song_Id INTEGER NOT NULL,
  Artist_Id INTEGER NOT NULL,
  PRIMARY KEY(Remix_Id, Song_Id, Artist_Id),
  FOREIGN KEY (Remix_Id) REFERENCES Remix(Id),
  FOREIGN KEY (Song_Id) REFERENCES Song(Id),
  FOREIGN KEY (Artist_Id) REFERENCES Artist(Id)
);
